name: Build

on:
    release:
      types:
        - created
    workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=mark-${{ matrix.os }} main.py

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mark-${{ matrix.os }}
          path: dist/mark-${{ matrix.os }}*
          if-no-files-found: error
        
      - name: Upload Release Asset
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/mark-${{ matrix.os }}.exe
          asset_name: mark-${{ matrix.os }}.exe
          asset_content_type: application/x-msdownload